### ISSUE TITLE
Regression 1.9.0: Mypy-0.930 crashes with INTERNAL ERROR when activating plugin with dataclasses

### ISSUE THREAD

**Issue by danigosa** [samuelcolvin/pydantic#3615]
### Checks

- [x] * [  ] I added a descriptive title to this issue
- [x] * [  ]  have searched (google, github) for similar issues and couldn't find anything
- [x] * [  ]  I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

**It works on Pydantic 1.8.x nd mypy 0.910**

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /home/danigosa/rbcode/.build/.virtualenvs/rblib-TD_A5kWe/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
                     platform: Linux-5.15.8-76051508-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
...
```

```bash
pipenv run mypy src/**/*.py --show-traceback
pipenv run mypy src/**/*.py --show-traceback
src/rblib/dataclasses.py:28: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.930
Traceback (most recent call last):
  File "mypy/semanal.py", line 5132, in accept
  File "mypy/nodes.py", line 1005, in accept
  File "mypy/semanal.py", line 1105, in visit_class_def
  File "mypy/semanal.py", line 1184, in analyze_class
  File "mypy/semanal.py", line 1193, in analyze_class_body_common
  File "mypy/semanal.py", line 1239, in apply_class_plugin_hooks
  File "mypy/plugins/dataclasses.py", line 486, in dataclass_class_maker_callback
  File "mypy/plugins/dataclasses.py", line 203, in transform
  File "mypy/plugins/dataclasses.py", line 467, in _add_dataclass_fields_magic_attribute
  File "mypy/semanal.py", line 4556, in named_type_or_none
AssertionError: Var:nil(Field)
src/rblib/dataclasses.py:28: : note: use --pdb to drop into pdb
...
```
```py
# -*- encoding: utf-8 -*-
"""Dataclasses with validation.
Using pydantic.dataclasses.dataclass for data validation
"""

from dataclasses import MISSING, Field, asdict  # type: ignore
from dataclasses import field as dtc_field
from dataclasses import fields, is_dataclass, replace  # type: ignore
from typing import Any, Dict, List, Mapping, Optional, Tuple, Type, TypeVar, Union, cast

from pydantic.dataclasses import dataclass
from rblib.serializers import json_dumps, json_loads, msgpack_dumps, msgpack_loads

__all__ = [
    "asdict",
    "fields",
    "replace",
    "is_dataclass",
    "field",
    "Base",
    "Schema",
]
TBase = TypeVar("TBase", bound="Base")
TSchema = TypeVar("TSchema", bound="Schema")


@dataclass
class Base:
    def to_dict(self: TBase) -> Union[Union[Tuple[Any], Dict[Any, Any]], Any]:
        return asdict(self)

    @classmethod
    def from_dict(
        cls: Type[TBase], obj: Union[List[Dict[Any, Any]], Dict[Any, Any]]
    ) -> Union[List[TBase], TBase]:
        # Retrieve only the fields necessary to create the instance
        if isinstance(obj, (list, tuple)):
            instances = list()
            for _obj in obj:
                vs = {f"{f.name}": _obj[f.name] for f in fields(cls) if f.name in _obj}
                instances.append(cls(**vs))  # type: ignore
            return instances

        vs = {f"{f.name}": obj[f.name] for f in fields(cls) if f.name in obj}
        return cls(**vs)  # type: ignore


@dataclass
class Schema(Base):
    def to_json(self: TSchema) -> TSchema:
        return cast(TSchema, json_dumps(self.to_dict()))

    @classmethod
    def from_json(cls: Type[TSchema], serialized: str) -> Union[List[TSchema], TSchema]:
        deserialized: Union[Dict[Any, Any], List[Dict[Any, Any]]] = json_loads(
            serialized
        )
        if isinstance(deserialized, list):
            instances: List[TSchema] = list()
            for obj in deserialized:
                instances.append(cast(TSchema, cls.from_dict(obj)))
            return instances

        return cls.from_dict(deserialized)

    def to_msgpack(self) -> Optional[bytes]:
        return cast(Optional[bytes], msgpack_dumps(self.to_dict()))

    @classmethod
    def from_msgpack(
        cls: Type[TSchema], serialized: bytes
    ) -> Union[List[TSchema], TSchema]:
        deserialized: Union[Dict[Any, Any], List[Dict[Any, Any]]] = msgpack_loads(
            serialized
        )
        if isinstance(deserialized, (list, tuple)):
            instances: List[TSchema] = list()
            for obj in deserialized:
                instances.append(cast(TSchema, cls.from_dict(obj)))
            return instances

        return cls.from_dict(deserialized)


def field(default_factory: Any = MISSING, **kwargs: Union[int, str, bool]) -> Field:
    return dtc_field(default_factory=default_factory, **kwargs)

```
```ini
[mypy]
plugins = pydantic.mypy
warn_redundant_casts = True
warn_unused_ignores = True
incremental = True

follow_imports = normal
ignore_missing_imports = True
disallow_any_generics = True
disallow_untyped_calls = True
disallow_untyped_defs = True
check_untyped_defs = True
warn_return_any = True
warn_no_return = True
no_implicit_reexport = True
strict_optional = True

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True
warn_untyped_fields = True
```
