### ISSUE TITLE
`pydantic-mypy` plugin is incompatible with `pyproject.toml` config in `mypy>0.900`

### ISSUE THREAD

**Issue by jrwalk** [samuelcolvin/pydantic#2895]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:

```
pydantic version: 1.8.2
pydantic compiled: True
   install path: /opt/venv/lib/python3.8/site-packages/pydantic
   python version: 3.8.5 (default, Sep 10 2020, 16:58:22)  [GCC 8.3.0]
       platform: Linux-5.10.25-linuxkit-x86_64-with-glibc2.2.5
optional deps. installed: ['typing-extensions']
```

The newest release of `mypy` (0.900-0.901) has introduced `pyproject.toml` configuration in addition to the older `mypy.ini` in accordance with PEP-518. However, the `pydantic-mypy` plugin still expects an INI-formatted config file, such that TOML-configured mypy with the plugin enabled results in a parse error:

```py
Error constructing plugin instance of PydanticPlugin

Traceback (most recent call last):
  File "/opt/venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/opt/venv/lib/python3.8/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 98, in main
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 229, in _build
  File "mypy/build.py", line 475, in load_plugins
  File "mypy/build.py", line 453, in load_plugins_from_config
  File "pydantic/mypy.py", line 77, in pydantic.mypy.PydanticPlugin.__init__
  File "pydantic/mypy.py", line 114, in pydantic.mypy.PydanticPluginConfig.__init__
  File "/usr/local/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/lib/python3.8/configparser.py", line 1113, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: 'pyproject.toml'
        [line 12]: ']\n'
        [line 17]: ']\n'
        [line 65]: ']\n'
...
```

Note that the plugin still works in `mypy>0.900` provided an INI configuration file is still provided. To bring the plugin up to speed for the newest mypy releases I believe we'll need a TOML parser option in addition to the default `ConfigParser` in the plugin constructor.

**Comment by johnthagen** [comment]
Should also update the user guide to show how to enable and configure the plugin for `pyproject.toml`. This will likely be what a vast majority of users will migrate to given how popular using `pyproject.toml` is becoming:

https://pydantic-docs.helpmanual.io/mypy_plugin/#enabling-the-plugin
https://pydantic-docs.helpmanual.io/mypy_plugin/#configuring-the-plugin

**Comment by jrwalk** [comment]
@johnthagen yep, I've got that in a PR I'm working on!

**Comment by johnthagen** [comment]
@jrwalk Upon further testing, the pydantic plugin does seem to be working at a basic level out of the box on a miniaturized example:

```py
# main.py
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, NoneStr


class Model(BaseModel):
    age: int
    first_name: str = 'John'
    last_name: NoneStr = None
    signup_ts: Optional[datetime] = None
    list_of_ints: List[int]


m = Model(age=42, list_of_ints=[1, '2', b'3'])
Model()  # will raise a validation error for age and list_of_ints
```

``` 
mypy main.py
main.py:15: error: Missing named argument "age" for "Model"
main.py:15: error: Missing named argument "list_of_ints" for "Model"
Found 2 errors in 1 file (checked 1 source file)
```

```toml
[tool.mypy]
ignore_missing_imports = true
strict = true

# Enable pydantic mypy plugin.
plugins = ["pydantic.mypy"]

# These configurations do not seem to be read:
[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
```

```
pip list
Package           Version
----------------- --------
click             8.0.1
mypy              0.902
mypy-extensions   0.4.3
pep517            0.10.0
pip               21.1.2
pip-tools         6.1.0
pydantic          1.8.2
setuptools        57.0.0
toml              0.10.2
typing-extensions 3.10.0.0
```

`mypy` has a hard dependency on `toml` now, so that can be assured to be installed.

**Comment by jrwalk** [comment]
Interesting - I wonder if that's trying to parse the toml file through `ConfigParser` (expecting INI syntax) and just happening to not hit syntax errors. In my test case the array fields (e.g. `plugins`) included newlines, which is valid TOML but broke in INI syntax. Judging by that error, I wonder if it's not correctly loading the plugin at all.

Adding the toml config reader is straightforward since we can piggyback off `mypy`'s own logic for determining the config file - only trick is the tests need a little updating since we'd need to bump the test dependency to `mypy>0.900`, which had some formatting changes on the output.

**Comment by johnthagen** [comment]
> In my test case

It would probably be good to post your `pyproject.toml` here so a known failure case is documented.

**Comment by jrwalk** [comment]
@johnthagen maybe moot since the PR is open, but

**Comment by jrwalk** [comment]
```toml
[tool.mypy]
ignore_missing_imports = true
strict = true

# Enable pydantic mypy plugin.
plugins = [
  "pydantic.mypy"
]

# These configurations do not seem to be read:
[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
```

should reproduce.

**Comment by hoefling** [comment]
Reading the config will fail as soon as TOML-specific stuff is present in `pyproject.toml`. E.g. adding
```toml
[[tool.mypy.overrides]]
module = "main"
no_implicit_reexport = true
```
or similar should already be enough to break the `ConfigParser`.

**Comment by jrwalk** [comment]
@hoefling yep, otherwise it's just luck whether the TOML doesn't contain invalid syntax for the ConfigParser. Fortunately adding a TOML parser isn't too difficult, so #2908 should resolve it

**Comment by hoefling** [comment]
@jrwalk I like it, even though I would really be tempted to use `pydantic` here :blush: Something like
```py
class PydanticPluginConfig(BaseModel):
    init_forbid_extra: bool = False
    init_typed: bool = False
    warn_required_dynamic_aliases: bool = False
    warn_untyped_fields: bool = False

def load(options: Options):
    if options.config_file.endswith('.toml'):
        with open(options.config_file, 'r') as rf:
            return PydanticPluginConfig(**toml.load(rf).get('tool', {}).get('pydantic-mypy', {}))
    else:
	cfg = ConfigParser()
        cfg.read(options.config_file)
        return parse_obj_as(PydanticPluginConfig, cfg["pydantic-mypy"])
```

**Comment by Ierezell** [comment]
Hi, I stumbled across this issue as I was trying to use the new norms (pyproject.toml) and I'm building an API with FastApi. 

Is there a branch or something I can help you testing with ? 

Have a great day.

**Comment by johnthagen** [comment]
@Ierezell See #2908, which references this branch: https://github.com/jrwalk/pydantic/tree/toml-support

**Comment by jrwalk** [comment]
@Ierezell feel free to use the branch @johnthagen linked, that should resolve it. And ++ to the thumbs-up as well - that mypy release is super fresh as well, so it just wouldn't have surfaced until very recently.

In the meantime, everything should work perfectly happily with `mypy>0.900`, just with the config in `mypy.ini` rather than `pyproject.toml` - and converting the config options back and forth is straightforward (the PR has an example to be added to the pydantic docs).

**Comment by Ierezell** [comment]
@johnthagen @jrwalk Thanks a lot for the informations and links ! 

I was using `mypy.ini` perfectly before but I switched to pdm and preferred to have all my config in one file. 
I know everything is bleeding edge new but I guess it take crash testers to check all that. 

I will install pydantic from your branch and come back.

Thanks for your work !

**Comment by ShadowLNC** [comment]
An interesting issue with VSCode is that if a linter crashes (as it does here), then it fails silently and doesn't warn you of any typing issues. I hit this "silent failure" with pylint config as well.

**Comment by johnthagen** [comment]
@PrettyWood Would it be possible to get a new release that includes this change? Thank you for working on this!

**Comment by samuelcolvin** [comment]
Not making any promises, but I'll try to get a new release or next week.

**Comment by christianbundy** [comment]
Thanks, really excited to see this released.

**Comment by christianbundy** [comment]
@samuelcolvin Is there anything we can do to help you get a new release out? Would it be helpful if I made prep branch like [this](https://github.com/samuelcolvin/pydantic/pull/2780)?

**Comment by randolf-scholz** [comment]
@christianbundy Until there is a new release it seems there is a simple workaround: I was also encountering errors of the form

```
configparser.ParsingError: Source contains parsing errors: 'pyproject.toml'
	[line 12]: ']\n'
```

and they apparently disappear after simply indenting the line. In my case:

```
[tool.pylint]
[tool.pylint.'MESSAGES CONTROL']
disable= [
    "C0103",  # invalid-name
    "C0144",  # non-ascii-name
    "R0801",  # similar lines
    "W0511",  # (fixme) (todos)
    ]
```

instead of 

```
[tool.pylint]
[tool.pylint.'MESSAGES CONTROL']
disable= [
    "C0103",  # invalid-name
    "C0144",  # non-ascii-name
    "R0801",  # similar lines
    "W0511",  # (fixme) (todos)
]
```

did the trick.

**Comment by jrwalk** [comment]
@randolf-scholz that's still passing the TOML through an INI parser, which I suspect could silently fail (or at least introduce weird settings) even in cases where it doesn't error out for invalid syntax. Have you verified that's actually setting all the configurations it ought to be?

**Comment by johnthagen** [comment]
1.9.0 release has been published with `pyproject.toml` support 🎉 
- https://pypi.org/project/pydantic/1.9.0/
