### ISSUE TITLE
"Config" overrides symbol of same name in class "BaseSettings"

### ISSUE THREAD

**Issue by adithep** [samuelcolvin/pydantic#4223]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
 pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /Users/adithepsrinarula/repo/prometheus-hoarding/dist/export/python/virtualenv/3.10.5/lib/python3.10/site-packages/pydantic
               python version: 3.10.5 (main, Jul  4 2022, 16:56:19) [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.4-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']

```

```py
import pydantic

class Settings(pydantic.BaseSettings):

    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"
```

I get error:

![Screen Shot 2565-07-09 at 18 33 49](https://user-images.githubusercontent.com/6279977/178103823-35166b3a-23eb-4a58-aa9d-3b6532a5cf9c.png)

**Comment by RobertCraigie** [comment]
@adithep Pylance is correct here. You have to explicitly subclass the `Config`, e.g.

```py
import pydantic

class Settings(pydantic.BaseSettings):
    class Config(pydantic.BaseSettings.Config):
        env_file = '.env'
        env_file_encoding = 'utf-8'
```

**Comment by jannisko** [comment]
Should this maybe be changed in the docs as well? The example given [here](https://pydantic-docs.helpmanual.io/usage/settings/) still causes an error in type checkers.

**Comment by DbCrWk** [comment]
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:

```
pydantic version: 1.9.2
            pydantic compiled: True
                 install path: /Users/dev.dabke/Documents/repo/ninja/nibbler/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, Jul 18 2022, 16:17:04) [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.5.1-arm64-arm-64bit
     optional deps. installed: ['devtools', 'dotenv', 'typing-extensions']
```


For what it's worth, running

> ```python
> import pydantic
> 
> class Settings(pydantic.BaseSettings):
>     class Config(pydantic.BaseSettings.Config):
>         env_file = '.env'
>         env_file_encoding = 'utf-8'
> ```

causes `mypy` to report:
```
Incompatible types in assignment (expression has type "str", base class "Config" defined the type as "None")
```
for the assignment `env_file = '.env'` and `env_file_encoding = 'utf-8'`.

I am running mypy version: `mypy 0.971 (compiled: yes)` and my `pyproject.toml` has this:
```toml
[tool.mypy]
plugins = [
    "pydantic.mypy"
]
```
Granted, the docs say that this plugin only works with `mypy` version 0.910, 0.920, 0.921 and 0.930, so maybe that is the issue?

CC: @RobertCraigie

**Comment by samuelcolvin** [comment]
pydantic should be compatible with all recent versions of mypy. This error is due to missing typing information on `pydantic.BaseSettings.Config`. Probably too late to fix this in V1.10, but we'll fix it in V2.

**Comment by samuelcolvin** [comment]
Ignore the above, @DbCrWk I've fixed your issue in #4450

**Comment by DbCrWk** [comment]
> Ignore the above, @DbCrWk I've fixed your issue in #4450

Wow, thanks for fixing this so quickly!

**Comment by gitpushdashf** [comment]
Thank you! This is great.

I am still seeing `class Config:` instead of `class Config(BaseSettings.Config):` in the documentation: https://docs.pydantic.dev/usage/settings/
