### ISSUE TITLE
1.9.0 -> 1.9.1: Nested jinja2.Template validation error

### ISSUE THREAD

**Issue by fatemonk** [samuelcolvin/pydantic#4291]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /home/ral/workspace/bork/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, Mar 24 2022, 16:12:56) [GCC 9.4.0]
                     platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

```py
from jinja2 import Template
from pydantic import BaseModel


class NestedItem(BaseModel):
    template: Template

    class Config:
        arbitrary_types_allowed = True


class Main(BaseModel):
    item: NestedItem


item = NestedItem(template=Template('<div>NI</div>'))
print(item)

main = Main(item=item)
print(main)
```

Expected result (`1.9.0` output):
```python
template=<Template memory:7fc4e9749b20>
item=NestedItem(template=<Template memory:7fc4e9749b20>)
```
Actual result (`1.9.1` output):
```python
template=<Template memory:7fbc994ae230>
Traceback (most recent call last):
  File "/home/ral/workspace/bork/playground/sandbox.py", line 21, in <module>
    b = Main(item=a)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Main
item
  Template.__new__() missing 1 required positional argument: 'source' (type=type_error)
```

**Comment by hramezani** [comment]
The change introduced in https://github.com/samuelcolvin/pydantic/commit/5490ad5173743ef2bf85216d11b9ff0822b3d25b when we change the normal copy to `deepcopy`.

But it's not a problem in `pydantic`. The error you mentioned is from `jinja2`. Take a look at [the related issue in jinja2](https://github.com/pallets/jinja/issues/758).

```python
>>> from copy import deepcopy
>>> from jinja2 import Template
>>> t = Template('')
>>> deepcopy(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hasan/.pyenv/versions/3.8.0/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/hasan/.pyenv/versions/3.8.0/lib/python3.8/copy.py", line 263, in _reconstruct
    y = func(*args)
  File "/home/hasan/.pyenv/versions/3.8.0/lib/python3.8/copyreg.py", line 91, in __newobj__
    return cls.__new__(cls, *args)
TypeError: __new__() missing 1 required positional argument: 'source'
```

You can fix it by adding [copy_on_model_validation option](https://pydantic-docs.helpmanual.io/usage/model_config/#options):

```python
from jinja2 import Template
from pydantic import BaseModel


class NestedItem(BaseModel):
    template: Template

    class Config:
        arbitrary_types_allowed = True
        copy_on_model_validation = False


class Main(BaseModel):
    item: NestedItem


item = NestedItem(template=Template('<div>NI</div>'))
print(item)

main = Main(item=item)
print(main)
```

**Comment by eseglem** [comment]
I was about to report a similar issue I experienced while moving from 1.9.0 to 1.9.1. Related to a sqlalchemy type, but due to the same move to deep copies. Looking at that change/issue it seems to have broken a number things. And having a bunch of code break upon an .. update isn't ideal.
